services:
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.minimal
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=postgresql://wazuh_user:wazuh_password@postgres:5432/wazuh_platform
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=wazuh_user
      - POSTGRES_PASSWORD=wazuh_password
      - POSTGRES_DB=wazuh_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: